# Week 2 Introduction to Programming with R

> by Lei Ding, Updated Feb. 2025

## 1. R数据结构

### 1.1 数组和矩阵

In [1]:
# 1. 向量与数组、矩阵的关系
z <- 1:1500  # 一维

dim(z) <- c(3, 5, 100)  # 设置维度
class(z)

dim(z) <- c(15, 100)  # 二维
class(z)

[1] "array"

[1] "matrix" "array"

In [2]:
# 2. 使用array函数创建数组
a <- array(1:20, dim=2)  # 一维数组，循环补齐（只取两个元素）
a

a <- array(1:20, dim=c(2))  # 一维数组
a

class(a)

[1] 1 2

[1] 1 2

[1] "array"

In [3]:
#
a <- array(1:20, dim=c(4, 5))  # 二维数组
a

a <- array(1:20, c(4, 6))  # 二维数组
class(a)

a <- array(1, c(3, 2))  # 二维数组
a

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17
[2,] 2    6    10   14   18
[3,] 3    7    11   15   19
[4,] 4    8    12   16   20

[1] "matrix" "array"

     [,1] [,2]
[1,] 1    1
[2,] 1    1
[3,] 1    1

In [1]:
# 注意：载入数组的方法是按列顺序，这与FORTRAN语言相同，不同于C语言
x <- array(1:24, dim=c(3, 4, 2))
x

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

In [5]:
# 3. 数组的索引
x[3, 2, 1]
# x[1, 2, 3]  # 第三个维度超出
x[3,, 1]
x[3,,]

[1] 6

[1]  3  6  9 12

     [,1] [,2]
[1,]  3   15
[2,]  6   18
[3,]  9   21
[4,] 12   24

In [6]:
# 4. 使用数组索引数组
x <- array(1:20, c(4, 5))
x

i <- array(c(1:3, 3:1), c(3, 2))
i

x[i] <- 0
x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17
[2,] 2    6    10   14   18
[3,] 3    7    11   15   19
[4,] 4    8    12   16   20

     [,1] [,2]
[1,] 1    3
[2,] 2    2
[3,] 3    1

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    5     0   13   17
[2,] 2    0    10   14   18
[3,] 0    7    11   15   19
[4,] 4    8    12   16   20

In [7]:
# 5. 使用matrix函数创建矩阵
m <- matrix(1:6, nrow=2)
m

matrix(1:6, ncol=3)

matrix(1:6, 2, byrow=TRUE)  # nrow=2，指定按行排序

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

In [8]:
# 注意：若行列元素不一致时，进行截取或循环补齐，并触发警告
matrix(1:6, 2, 4)
matrix(1:6, 2, 2)

Warning message in matrix(1:6, 2, 4):
“data length [6] is not a sub-multiple or multiple of the number of columns [4]”

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    1
[2,] 2    4    6    2

Warning message in matrix(1:6, 2, 2):
“data length differs from size of matrix: [6 != 2 x 2]”

     [,1] [,2]
[1,] 1    3
[2,] 2    4

In [9]:
# 6. 使用比较运算符索引矩阵
m <- matrix(1:6, 2)
m

m[1,] <= 3

m[, m[1,] <= 3]

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

[1]  TRUE  TRUE FALSE

     [,1] [,2]
[1,] 1    3
[2,] 2    4

In [10]:
# 7. 使用which函数索引矩阵
m <- matrix(1:6, 2)
which(m > 2)

[1] 3 4 5 6

In [11]:
# 8. 使用元素名称索引矩阵
m <- matrix(1:6, 2)
rownames(m) <- c('row1', 'row2')
colnames(m) <- c('col1', 'col2', 'col3')
m

m['row2', 'col3']
m[2, 3]  # 仍可用下标索引

     col1 col2 col3
row1 1    3    5
row2 2    4    6

[1] 6

[1] 6

In [12]:
# 9. 替换值
m <- matrix(1:6, 2)
m[1,] <- 999
m

     [,1] [,2] [,3]
[1,] 999  999  999
[2,]   2    4    6

In [13]:
# 10. 矩阵的横向合并与纵向合并
m <- matrix(1:6, 2)
p <- matrix(7:12, 2)

cbind(m, p)  # 要求行数一致
rbind(m, p)  # 要求列数一致

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11
[2,] 2    4    6    8    10   12

     [,1] [,2] [,3]
[1,] 1     3    5
[2,] 2     4    6
[3,] 7     9   11
[4,] 8    10   12

In [14]:
# 11. 按行/列加和与平均值
m <- matrix(1:12, 3, 4)
m

rowSums(m)
rowMeans(m)

colSums(m)
colMeans(m)

sum(m)
mean(m)

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

[1] 22 26 30

[1] 5.5 6.5 7.5

[1]  6 15 24 33

[1]  2  5  8 11

[1] 78

[1] 6.5

In [15]:
# 12. 矩阵逐元素算术运算
A = matrix(1:6, 2)
A * A  # 逐元素乘法
#A %*% A  # 矩阵乘法要求矩阵形状满足要求

B = matrix(1:6, 3)
A %*% B

     [,1] [,2] [,3]
[1,] 1     9   25
[2,] 4    16   36

     [,1] [,2]
[1,] 22   49
[2,] 28   64

In [16]:
# 13. apply函数：将函数作用到数组的若干维度上
x <- matrix(1:20, 10)
x

apply(x, 2, mean)  # margin=2，作用的维度（作用到列上）

colMeans(x)

      [,1] [,2]
 [1,]  1   11
 [2,]  2   12
 [3,]  3   13
 [4,]  4   14
 [5,]  5   15
 [6,]  6   16
 [7,]  7   17
 [8,]  8   18
 [9,]  9   19
[10,] 10   20

[1]  5.5 15.5

[1]  5.5 15.5

In [17]:
#
x <- matrix(1:6, 3)
f <- function(x) { return (x / c(2, 8)) }
apply(x, 1, f)  # 作用到行上

     [,1] [,2]  [,3]
[1,] 0.5  1.000 1.50
[2,] 0.5  0.625 0.75

In [18]:
# 14. t函数：转置矩阵
x = matrix(1:6, 3)
x
t(x)

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

### 1.2 数据框

In [19]:
# 15. 内置数据集
class(mtcars)
dim(mtcars)
nrow(mtcars)
ncol(mtcars)

colnames(mtcars)
rownames(mtcars)
data.matrix(mtcars)

[1] "data.frame"

[1] 32 11

[1] 32

[1] 11

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"
 [7] "Duster 360"          "Merc 240D"           "Merc 230"
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood"
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"
[31] "Maserati Bora"       "Volvo 142E"

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [20]:
# 16. 一些查看数据信息的有用函数
head(mtcars)
tail(mtcars, 3)
str(mtcars)  # 结构
summary(mtcars)  # 摘要

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

              mpg  cyl disp hp  drat wt   qsec vs am gear carb
Ferrari Dino  19.7 6   145  175 3.62 2.77 15.5 0  1  5    6
Maserati Bora 15.0 8   301  335 3.54 3.57 14.6 0  1  5    8
Volvo 142E    21.4 4   121  109 4.11 2.78 18.6 1  1  4    2

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

      mpg             cyl             disp             hp
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5
 Median :19.20   Median :6.000   Median :196.3   Median :123.0
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0
      drat             wt             qsec             vs
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000
       am              gear            carb
 Min.   :0.0000   Min.   :3.000   Min.   :1.000
 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000
 Median :0.0000   Median :4.000   Median :2.000
 Mean   :0.4062   Mean   :3.688   Mean   :2.812
 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000
 Max.   :1.0000   Max.   :5.000   Max.   :8.000

In [21]:
# 17. 从向量创建数据框
Name <- c('John', 'Bill', 'Maria', 'Ben', 'Tina')
Age <- c(23, 41, 32, 58, 26)

df <- data.frame(Name, Age)
df

  Name  Age
1 John  23
2 Bill  41
3 Maria 32
4 Ben   58
5 Tina  26

In [22]:
# 18. 数据框摘要
summary(df)

     Name                Age
 Length:5           Min.   :23
 Class :character   1st Qu.:26
 Mode  :character   Median :32
                    Mean   :36
                    3rd Qu.:41
                    Max.   :58

In [23]:
# 19. 数据框索引
df[2,]
df[, 1]
df[1:4, 'Age']
df$Name
df[[2, 2]]

  Name Age
2 Bill 41

[1] "John"  "Bill"  "Maria" "Ben"   "Tina"

[1] 23 41 32 58

[1] "John"  "Bill"  "Maria" "Ben"   "Tina"

[1] 41

In [24]:
# 20. 获取某一列的四种方法
mtcars$mpg
mtcars[,1]  # mtcars[1]仍为数据框
mtcars[,'mpg']
mtcars[['mpg']]  # 单方框号返回子集，双方框号返回元素

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [25]:
# 21. 使用subset选取
subset(mtcars, hp>200)

subset(mtcars, cyl==6)

                    mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Duster 360          14.3 8   360  245 3.21 3.570 15.84 0  0  3    4
Cadillac Fleetwood  10.4 8   472  205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460  215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440  230 3.23 5.345 17.42 0  0  3    4
Camaro Z28          13.3 8   350  245 3.73 3.840 15.41 0  0  3    4
Ford Pantera L      15.8 8   351  264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301  335 3.54 3.570 14.60 0  1  5    8

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Valiant        18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 280       19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C      17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6

In [26]:
# 22. 使用order排序
mtcars[order(mtcars$mpg, decreasing=TRUE),]  # 所有行按mpg列排序

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4

In [27]:
# 23. 使用merge函数合并数据框
x <- data.frame(k1=1:3, k2=4:6)
y <- data.frame(k1=c(1, 3), k2=11:12)
x
y

merge(x, y)
merge(x, y, by='k1')  # 指定同名列
merge(x, y, by='k1', all.x=T)  # 包含所有x的列

  k1 k2
1 1  4
2 2  5
3 3  6

  k1 k2
1 1  11
2 3  12

     k1 k2

  k1 k2.x k2.y
1 1  4    11
2 3  6    12

  k1 k2.x k2.y
1 1  4    11
2 2  5    NA
3 3  6    12

### 1.3 列表与因子

In [28]:
# 24. 列表是一个具有不同类型元素的向量
x <- list(1, 'a', TRUE, 500)
x

class(x)
mode(x)
typeof(x)

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 500

[1] "list"

[1] "list"

[1] "list"

In [29]:
# 25. 键值对的形式
x <- list(name='Lucy', age=30, male=FALSE)
x
x$age

$name
[1] "Lucy"

$age
[1] 30

$male
[1] FALSE

[1] 30

In [30]:
# 26. 列表嵌套
x <- list(list(name='Lucy', age=30, male=FALSE), list(name='James', age=18, male=TRUE))
x

x[[1]]$age

[[1]]
[[1]]$name
[1] "Lucy"

[[1]]$age
[1] 30

[[1]]$male
[1] FALSE


[[2]]
[[2]]$name
[1] "James"

[[2]]$age
[1] 18

[[2]]$male
[1] TRUE

[1] 30

In [31]:
# 27. 创建因子
x <- factor(c('yes', 'yes', 'no', 'yes', 'no'))
x

table(x)  # 生成频数表

[1] yes yes no  yes no
Levels: no yes

x
 no yes
  2   3

In [32]:
# 28. 有序因子
temp <- factor(c('high', 'low', 'high', 'medium', 'low'), levels=c('low', 'medium', 'high'), ordered=TRUE)
temp

min(temp)  # 有序因子可计算最值

[1] high   low    high   medium low
Levels: low < medium < high

[1] low
Levels: low < medium < high

In [33]:
# 29. tapply函数按照因子分组聚合
temp <- c(10, 4, 27, 31, -10, -25, 35)
tlevel <- factor(c('medium', 'medium', 'high', 'high', 'low', 'low', 'high'))

tapply(temp, tlevel, mean)
tapply(temp, tlevel, range)

  high    low medium
  31.0  -17.5    7.0

$high
[1] 27 35

$low
[1] -25 -10

$medium
[1]  4 10

In [34]:
#
x <- data.frame(gender=factor(c('M', 'M', 'F', 'M', 'F', 'F')),
                ages=c(21, 25, 27, 54, 20, 32),
                income=c(24000, 31000, 44000, 31000, 22000, 60000))
x

x$over25 <- ifelse(x$age > 25, 1, 0)  #新增over25列
x

tapply(x$income, list(x$gender, x$over25), mean)  # 按照两列分组

  gender ages income
1 M      21   24000
2 M      25   31000
3 F      27   44000
4 M      54   31000
5 F      20   22000
6 F      32   60000

  gender ages income over25
1 M      21   24000  0
2 M      25   31000  0
3 F      27   44000  1
4 M      54   31000  1
5 F      20   22000  0
6 F      32   60000  1

  0     1
F 22000 52000
M 27500 31000

In [35]:
# 30. split函数分组
x
split(x, x$gender)

  gender ages income over25
1 M      21   24000  0
2 M      25   31000  0
3 F      27   44000  1
4 M      54   31000  1
5 F      20   22000  0
6 F      32   60000  1

$F
  gender ages income over25
3      F   27  44000      1
5      F   20  22000      0
6      F   32  60000      1

$M
  gender ages income over25
1      M   21  24000      0
2      M   25  31000      0
4      M   54  31000      1

## 2. 数据的输入与输出

In [36]:
# 31. 读写CSV文件
write.csv(mtcars, file='example.csv')
df <- read.csv('example.csv')
head(df)

  X                 mpg  cyl disp hp  drat wt    qsec  vs am gear carb
1 Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
2 Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
3 Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
4 Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
5 Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
6 Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [37]:
# 32. UCI数据集操作（https://archive.ics.uci.edu/ml/index.php）
iris = read.csv('iris/iris.data')
names(iris) <- c('sepal length', 'sepal width', 'petal length', 'petal width', 'class')
iris$class <- factor(iris$class)  # 最后一列转为因子
head(iris)

  sepal length sepal width petal length petal width class
1 4.9          3.0         1.4          0.2         Iris-setosa
2 4.7          3.2         1.3          0.2         Iris-setosa
3 4.6          3.1         1.5          0.2         Iris-setosa
4 5.0          3.6         1.4          0.2         Iris-setosa
5 5.4          3.9         1.7          0.4         Iris-setosa
6 4.6          3.4         1.4          0.3         Iris-setosa

In [38]:
# 33. 读写Excel文件
library('readxl')
df <- read_excel('mtcars.xlsx', sheet=1)
df

   name                mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
2  Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
3  Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
4  Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
5  Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
6  Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
7  Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
8  Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
9  Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
10 Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
11 Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
12 Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
13 Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
14 Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
15 Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
16 Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
17 Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
18 Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
19 Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
20 Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
21 Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
22 Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
23 AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
24 Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
25 Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
26 Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
27 Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
28 Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
29 Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
30 Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
31 Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
32 Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

## 3. 一些有用的函数

In [39]:
# 34. 缺失值处理
x <- c(1, 2, NA, 10, 3)
is.na(x)  # 同时检测NA和NaN
is.nan(x)

x[is.na(x) | is.nan(x)] <- mean(x, na.rm=TRUE)
x

[1] FALSE FALSE  TRUE FALSE FALSE

[1] FALSE FALSE FALSE FALSE FALSE

[1]  1  2  4 10  3

In [40]:
#
y <- c(1, 2, NaN, NA, 4)
is.na(y)
is.nan(y)

[1] FALSE FALSE  TRUE  TRUE FALSE

[1] FALSE FALSE  TRUE FALSE FALSE

In [41]:
# 35. describe函数
library(psych)  # psychological methods
describe(mtcars)

     vars n  mean       sd          median  trimmed     mad         min
mpg   1   32  20.090625   6.0269481  19.200  19.6961538   5.4114900 10.400
cyl   2   32   6.187500   1.7859216   6.000   6.2307692   2.9652000  4.000
disp  3   32 230.721875 123.9386938 196.300 222.5230769 140.4763500 71.100
hp    4   32 146.687500  68.5628685 123.000 141.1923077  77.0952000 52.000
drat  5   32   3.596563   0.5346787   3.695   3.5792308   0.7042350  2.760
wt    6   32   3.217250   0.9784574   3.325   3.1526923   0.7672455  1.513
qsec  7   32  17.848750   1.7869432  17.710  17.8276923   1.4158830 14.500
vs    8   32   0.437500   0.5040161   0.000   0.4230769   0.0000000  0.000
am    9   32   0.406250   0.4989909   0.000   0.3846154   0.0000000  0.000
gear 10   32   3.687500   0.7378041   4.000   3.6153846   1.4826000  3.000
carb 11   32   2.812500   1.6152000   2.000   2.6538462   1.4826000  1.000
     max     range   skew       kurtosis    se
mpg   33.900  23.500  0.6106550 -0.37276603  1.06542396
cyl    8.000   4.000 -0.1746119 -1.76211977  0.31570933
disp 472.000 400.900  0.3816570 -1.20721195 21.90947271
hp   335.000 283.000  0.7260237 -0.13555112 12.12031731
drat   4.930   2.170  0.2659039 -0.71470062  0.09451874
wt     5.424   3.911  0.4231465 -0.02271075  0.17296847
qsec  22.900   8.400  0.3690453  0.33511422  0.31588992
vs     1.000   1.000  0.2402577 -2.00193762  0.08909831
am     1.000   1.000  0.3640159 -1.92474143  0.08820997
gear   5.000   2.000  0.5288545 -1.06975068  0.13042656
carb   8.000   7.000  1.0508738  1.25704307  0.28552971

## 4. R语言编程结构

In [42]:
# 36. If语句
clod <- FALSE
temp <- 3

if (temp < 10) {
    cold <- TRUE
}

cold

[1] TRUE

In [43]:
#
x <- 0

if (x > 3) {
    y <- 1
} else if (x <= 3 && x > 0) {
    y <- 0
} else {
    y <- -1
}

y

[1] -1

In [44]:
# 37. for循环语句
x <- c(1, 5, 4, 3, 2)

for (i in 1:length(x)) {
    print(x[i])
}

[1] 1
[1] 5
[1] 4
[1] 3
[1] 2

In [45]:
#
x <- matrix(1:6, 2)
x

for (i in seq_len(nrow(x))) {
    for (j in seq_len(ncol(x))) {
        print(x[i, j])
    }
}

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

[1] 1
[1] 3
[1] 5
[1] 2
[1] 4
[1] 6

In [46]:
# 38. while循环语句
i <- 1

while (i < 5) {
    print(i)
    i <- i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4

In [47]:
# 39. repeat循环语句
v <- c('Hello', 'loop')
cnt <- 2

repeat {
    print(v)
    cnt <- cnt + 1
    
    if (cnt > 5) {
        break
    }
}

[1] "Hello" "loop"
[1] "Hello" "loop"
[1] "Hello" "loop"
[1] "Hello" "loop"

In [48]:
# 40. next语句
v <- LETTERS[1:6]

for (i in v) {
    if (i == "D") {
        next
    }
    print(i)
}

[1] "A"
[1] "B"
[1] "C"
[1] "E"
[1] "F"

In [49]:
# 41. 函数
f <- function(a, b) {
    y <- a * b
    return(y)
}

f(2, 3)
f(b=3, a=2)

[1] 6

[1] 6

In [50]:
# 42. 变量作用域
w <- 12

f <- function(y) {
    d <- 8
    h <- function() {
        return(d * (w + y))
    }
    return(h())
}

f(2)

[1] 112

In [51]:
#
y <- 10

f <- function(x) {
    y <- 2  # 局部变量
    y ^ 2 + g(x)
}

g <- function(x) {
    x * y  # 全局变量
}

f(3)

[1] 34